export const inboxConversations = [
  {
    id: 'conv-anjali',
    contactName: 'Anjali Mehta',
    businessName: 'Anjali Saree House',
    phone: '+91 98765 43210',
    city: 'Indore',
    preview: 'Need festive kurti options for 25 pieces next week.',
    lastMessageTime: '10:42 AM',
    unreadCount: 2,
    replyState: 'Awaiting reply',
    stage: 'Qualified',
    assignee: 'Riya',
    messages: [
      {
        id: 'm1',
        sender: 'contact',
        text: 'Hi, can you share festive kurti options for my store?',
        time: '10:18 AM',
      },
      {
        id: 'm2',
        sender: 'user',
        text: 'Sure. Are you looking for retail pieces or a bulk order?',
        time: '10:26 AM',
      },
      {
        id: 'm3',
        sender: 'contact',
        text: 'Bulk order. Around 25 pieces if pricing works.',
        time: '10:42 AM',
      },
    ],
    lead: {
      contactName: 'Anjali Mehta',
      businessName: 'Anjali Saree House',
      phone: '+91 98765 43210',
      email: 'anjali@sareehouse.in',
      stage: 'Qualified',
      owner: 'Riya',
      source: 'Instagram DM',
      city: 'Indore',
      paymentStatus: 'Not started',
      estimatedValue: 'Rs 38,000',
      tags: ['Wholesale', 'Festive'],
      notes: [
        {
          id: 'n1',
          text: 'Requested mixed sizes and catalog pricing for Akshaya Tritiya stock.',
          time: 'Today',
        },
        {
          id: 'n2',
          text: 'Prefers dispatch before Friday if order is confirmed.',
          time: 'Today',
        },
      ],
      lastActivity: 'Today, 10:42 AM',
    },
  },
  {
    id: 'conv-noor',
    contactName: 'Noor Boutique',
    businessName: 'Noor Boutique',
    phone: '+91 98111 22113',
    city: 'Lucknow',
    preview: 'Can someone confirm if the rose set is available in M and L?',
    lastMessageTime: '9:18 AM',
    unreadCount: 1,
    replyState: 'Unread',
    stage: 'Contacted',
    assignee: 'Pooja',
    messages: [
      {
        id: 'm1',
        sender: 'contact',
        text: 'Can someone confirm if the rose set is available in M and L?',
        time: '9:18 AM',
      },
    ],
    lead: {
      contactName: 'Sara Khan',
      businessName: 'Noor Boutique',
      phone: '+91 98111 22113',
      email: 'hello@noorboutique.in',
      stage: 'Contacted',
      owner: 'Pooja',
      source: 'WhatsApp referral',
      city: 'Lucknow',
      paymentStatus: 'Pending payment link',
      estimatedValue: 'Rs 12,400',
      tags: ['Retail'],
      notes: [
        {
          id: 'n1',
          text: 'Asked for ready stock and wants quick delivery within 2 days.',
          time: 'Today',
        },
      ],
      lastActivity: 'Today, 9:18 AM',
    },
  },
  {
    id: 'conv-greenleaf',
    contactName: 'GreenLeaf Naturals',
    businessName: 'GreenLeaf Naturals',
    phone: '+91 98222 44556',
    city: 'Pune',
    preview: 'New chat opened from website campaign.',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    replyState: 'New lead',
    stage: 'New',
    assignee: 'Unassigned',
    messages: [],
    lead: {
      contactName: 'Maya Kulkarni',
      businessName: 'GreenLeaf Naturals',
      phone: '+91 98222 44556',
      email: 'maya@greenleafnaturals.in',
      stage: 'New',
      owner: 'Unassigned',
      source: 'Website campaign',
      city: 'Pune',
      paymentStatus: 'Not started',
      estimatedValue: 'TBD',
      tags: [],
      notes: [],
      lastActivity: 'Yesterday, 6:10 PM',
    },
  },
  {
    id: 'conv-rk',
    contactName: 'R K Coaching Centre',
    businessName: 'R K Coaching Centre',
    phone: '+91 98980 77765',
    city: 'Jaipur',
    preview: 'Please send the payment link for the second batch.',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    replyState: 'Follow up today',
    stage: 'Won',
    assignee: 'Aman',
    messages: [
      {
        id: 'm1',
        sender: 'contact',
        text: 'Please send the payment link for the second batch.',
        time: 'Yesterday, 5:30 PM',
      },
      {
        id: 'm2',
        sender: 'user',
        text: 'Noted. We will prepare it in the payment module.',
        time: 'Yesterday, 5:36 PM',
      },
    ],
    lead: {
      contactName: 'Rohit Khandelwal',
      businessName: 'R K Coaching Centre',
      phone: '+91 98980 77765',
      email: 'rohit@rkcoaching.in',
      stage: 'Won',
      owner: 'Aman',
      source: 'Existing customer',
      city: 'Jaipur',
      paymentStatus: 'Partially paid',
      estimatedValue: 'Rs 64,000',
      tags: ['Repeat customer', 'Priority'],
      notes: [
        {
          id: 'n1',
          text: 'Returning customer. Wants separate payment links for each student batch.',
          time: 'Yesterday',
        },
      ],
      lastActivity: 'Yesterday, 5:36 PM',
    },
  },
]

export const inboxStats = {
  totalConversations: inboxConversations.length,
  unreadConversations: inboxConversations.filter(
    (conversation) => conversation.unreadCount > 0,
  ).length,
  awaitingReply: inboxConversations.filter(
    (conversation) => conversation.replyState === 'Awaiting reply',
  ).length,
}

